---
jenkins_version: latest
jenkins_home: /var/jenkins_home

configs: [
  { src: "credentials.xml", dir: "/var/jenkins_home", file: "credentials.xml", mode: "0777" },
  { src: "scriptApproval.xml", dir: "/var/jenkins_home", file: "scriptApproval.xml", mode: "0644" }
]
