---
- name: Container is running
  docker_container:
    name: jenkins
    image: "jenkins:{{ jenkins_version }}"
    ports: 8080:8080
    volumes:
      - "{{ jenkins_home_dir }}:/var/jenkins_home"

